### PR TITLE
#31 num 0 is int

### PR DESCRIPTION
**Pull request by maxonfjvipon**

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur I think it's good to merge

**Comment by Graur** [comment]
@maxonfjvipon Good one, but what will be returned if we check this: `(number 0).as-float` ?

**Comment by maxonfjvipon** [comment]
@Graur it'll be an exception (divided by zero). Got your idea, will fix it

**Comment by maxonfjvipon** [comment]
@Graur could you please tell me how it works?)
image
image

**Comment by maxonfjvipon** [comment]
@Graur could you please tell me what's going on here. Idk why but I can't properly make `as-int` and `as-float`
image
image

**Comment by maxonfjvipon** [comment]
@Graur I found out that both `0.eq 0.0` and `0.0.eq 0` are `TRUE`. So if we accept this: 
1. `(number 0).is-int` = true,
2. `(number 0.0).is-int` = true (scope of integers is less than scope of floats, so I think 0.0 should be kind of cast), 
3. `(number 0).is-float` = false
4. `(number 0.0).is-float` = false (check p.2)

**Comment by Graur** [comment]
@maxonfjvipon Maybe we can think about exception throwing solution. e.g.
```
...
if.
  ^.eq 0
  try
    []
      (^.plus 1).eq 1 > @
    [ex]
      FALSE > @
...
What do you think?
```

**Comment by maxonfjvipon** [comment]
@Graur looks good, I'll try it out

**Comment by maxonfjvipon** [comment]
@Graur it works now. I also improved `mod` object, it throws StackOverflow exception with these new `is-int`. It seems for better performance we should cache every object that we copy inside other object (`^.n > value!` instead of `^.n > value`) or am I wrong?

**Comment by Graur** [comment]
@maxonfjvipon You are right. Let's do this

**Comment by maxonfjvipon** [comment]
@Graur should I do it only inside `is-int` and `is-float` objects or inside while `number`?

**Comment by Graur** [comment]
@maxonfjvipon I think it would be better to use it only inside nested objects

**Comment by Graur** [comment]
@maxonfjvipon Can you link the relevant issue in PR comments? e.g. #31

**Comment by maxonfjvipon** [comment]
@Graur Sure, but I thought that this is enough:
image
It links commit to the issue. Or you want that I use the link with every comment?

**Comment by Graur** [comment]
> @Graur Sure, but I thought that this is enough: image It links commit to the issue. Or you want that I use the link with every comment?

If you tag in PR related issue, `rultor` close it, when PR will be merged.
The right syntax is: Closes: #31

**Comment by maxonfjvipon** [comment]
Closes: #31

**Comment by Graur** [comment]
@yegor256 please, have a look

**Comment by yegor256** [comment]
@maxonfjvipon @Graur this is called "exception as flow control" and it's an anti pattern: https://softwareengineering.stackexchange.com/questions/189222/are-exceptions-as-control-flow-considered-a-serious-antipattern-if-so-why

**Comment by maxonfjvipon** [comment]
@yegor256 Ok, `try catch` in that case is a bad idea. Then we need to solve `0.eq 0.0 => true` problem.

**Comment by Graur** [comment]
@maxonfjvipon let's get back to your idea
@yegor256 what do you think about this solution:
`(number 0).is-int` = true,
`(number 0.0).is-int` = true (scope of integers is less than scope of floats, so I think 0.0 should be kind of cast),
`(number 0).is-float` = false
`(number 0.0).is-float` = false (check p.2)

**Comment by maxonfjvipon** [comment]
@Graur mb we can left this "anti pattern try catch flow control" solution until we solve [this](https://github.com/objectionary/eo/issues/942)? Because 0.0 is float after all, not int

**Comment by Graur** [comment]
@maxonfjvipon Maybe let's implement it as if the task in EO has already been completed. If some tests fail, just decorate them by `nop` object.

**Comment by maxonfjvipon** [comment]
@Graur could you please tell me what's wrong with build on windows?

**Comment by Graur** [comment]
@maxonfjvipon It is a general issue. We are working on it

**Comment by maxonfjvipon** [comment]
@yegor256 @Graur can we merge this and add to objectionary before [this one](https://github.com/objectionary/eo/pull/957). It seems it should solve the whole problem (read [here](https://github.com/objectionary/eo/pull/957#issuecomment-1200153890))

**Comment by Graur** [comment]
@maxonfjvipon let me first fix workflow build here

**Comment by Graur** [comment]
@yegor256 Can we rerun these checks ? This task is a part of https://github.com/objectionary/eo/issues/942

**Comment by yegor256** [comment]
@Graur just push something new to the branch

**Comment by maxonfjvipon** [comment]
@yegor256 I think it's good to merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
