### PR TITLE
#53 Introduced number.log and number.ln

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #53

There are no tests for now.

@Graur could you please take a look at this code inside EOnumber$EOln:
```java
final double self = (Double) base;
  if (self < 0.0d) {
      phi = new EOnan(sigma);
  } else if (self == 0.0d) {
      phi = new EOnegative_infinity(sigma);
  } else if (self == 1.0d) {
      phi = new Data.ToPhi(0.0d);
  } else {
      phi = new Data.ToPhi(Math.log(self));
  }
```

As we know `ln(a) = NaN` when `a < 0`. My question is: can I create and return here `EOnan` and if I can what variable should I pass to it as an argument (`sigma`)?

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur could you please take a look what's wrong with windows build?

**Comment by Graur** [comment]
@maxonfjvipon Maybe `new EOnan(rho)` would be better

**Comment by Graur** [comment]
@maxonfjvipon  Please, restart your build

**Comment by maxonfjvipon** [comment]
@Graur please take a look

**Review by Graur — APPROVED** [review]
@maxonfjvipon Looks good to me
@yegor256 Please, have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
