### PR TITLE
EO version was up

### PR DESCRIPTION
**Pull request by Graur**
What's done:

- disabled several tests
- added todo
- increased EO version to 0.29.1

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 Can you help to stop `Windows` checks? I want to see output log of these tests. But they are stuck

**Comment by yegor256** [comment]
@Graur done

**Comment by Graur** [comment]
> Details

Thanks! Now I find the way to check GA logs by myself

**Comment by Graur** [comment]
@yegor256 I didn't find out why are these tests failing. But I create a puzzle and disable them. Can you take a look, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
