### PR TITLE
Remove `nan` and infinites from the package

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #105

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur am I right that updating `eo-maven-plugin` dependency to `0.29.0` that contains `nan` and +- infs is not enough? We should add these objects to `objectionary/home` before?

**Comment by Graur** [comment]
@maxonfjvipon Yes, you are right. I will try to create new pull request in `home`

**Comment by maxonfjvipon** [comment]
@Graur please have a look

**Review by Graur — APPROVED** [review]
@maxonfjvipon Looks good, thanks!
@yegor256 Please, have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@yegor256 please try to merge one more time

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
