### PR TITLE
#13 Moved angle, number and randrom from eo to math

### PR DESCRIPTION
**Pull request by maxonfjvipon**

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur could you please tell me why `pdd-lint` does not pass?

**Comment by Graur** [comment]
@maxonfjvipon This is a temporary problem in all projects with `pdd`, I believe we will fix it soon

**Comment by maxonfjvipon** [comment]
@Graur ok, then I think it's good to merge, isn't it?

**Comment by maxonfjvipon** [comment]
@rultor merge

**Comment by Graur** [comment]
@maxonfjvipon Everything looks great to me!

**Comment by maxonfjvipon** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@Graur Any ideas why Rultor can't merge it?

**Comment by Graur** [comment]
@maxonfjvipon I see just an error message of transpiler, which tell us about `?` mark in path `EOorg/EOeolang/EOmath/EOpositive_infinity$EOas_int$EO?.java`.  Maybe eolang version up to latest in `pom.xml` can help.

**Comment by Graur** [comment]
@maxonfjvipon Or maybe we can redo object `as-int` in `positive_infinity` to
```
[] as-int
   "some message" > msg
```
and try again merge this PR with rultor

**Comment by maxonfjvipon** [comment]
@Graur After version eolang up build fails. Duplicates cause it.

image

It seems, I should make a PR with removing these objects to eo-runtime first

**Comment by Graur** [comment]
@maxonfjvipon Indeed, my bad. I think we should release your eo-math project first. Then add it to objectionary/home. And then remove math package from eo-runtime.
So, keeping lowest version of EO is a smart move. Let's rollback and try to change positive-infinity

**Comment by maxonfjvipon** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@Graur Did I miss something? Why don't we need to make an abstract object to throw an exception?
```
[] > as-int
  "Message" > msg
  # instead of
  # [] > @
  #   "Message" > msg
```
Or it's some sort of a bug?

**Comment by Graur** [comment]
@maxonfjvipon You are absolutely right! It was just my guess. So, maybe there is some problem with rultor. Let me check it in other repository.

**Comment by Graur** [comment]
@maxonfjvipon `rultor` works well

**Comment by maxonfjvipon** [comment]
@rultor merge

**Comment by maxonfjvipon** [comment]
@Graur Can we still merge it manually this time? It seems there are not any troubles, it builds fine

**Pull request merged**
