### PR TITLE
#31 num 0 is int (tests)

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #31

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur let it be here until `eo` includes `0.eq 0.0 => false` to release

**Comment by maxonfjvipon** [comment]
@Graur could you please take a look?
Failed to execute goal org.eolang:eo-maven-plugin:0.28.0:assemble (compile) on project eo-math: Execution compile of goal org.eolang:eo-maven-plugin:0.28.0:assemble failed: Tag 'master' doesn't exist or the list of all tags was not loaded correctly

**Comment by Graur** [comment]
@maxonfjvipon I tried to run build with the eo-math project's EO version and with 0.28.2 - they both passed. So, could you try to rerun your build again? Maybe just by changing the EO version

**Comment by maxonfjvipon** [comment]
@Graur I think it's good to merge. We can close: #31 and #44

**Review by Graur — APPROVED** [review]
@yegor256 Please, have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
