### PR TITLE
refactor(#136): update eo version, refactor objects and tests

### PR DESCRIPTION
**Pull request by maxonfjvipon**
Closes: #136

---

### Focus of this PR:
Update dependencies and make code improvements.

### Detailed summary:
- Updated the version of eo-runtime from 0.30.0 to 0.32.0.
- Updated the version of eo-maven-plugin from 0.29.4 to 0.32.0.
- Added a new package `org.eolang.math` and updated the home URL to `https://github.com/objectionary/eo-math`.
- Renamed `series` alias to `assert-that` and added a new `series` alias.
- Modified the `number-tests.eo` file to fix a bug related to type conversion.
- Modified the `series.eo` file to improve error handling and add a new method.
- Updated the version of eo-runtime in the `pom.xml` file from 0.30.0 to 0.32.0.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur please review this one

**Review by Graur — APPROVED** [review]
@maxonfjvipon Good one!

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
