### PR TITLE
refactored `log` object 

### PR DESCRIPTION
**Pull request by Graur**
#71

Due to avoid StackOverflow error I have refactored `log` object

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 Please, have a look

**Comment by maxonfjvipon** [comment]
@Graur it seems in such complex objects we should not use `switch` for now

**Comment by yegor256** [comment]
@Graur maybe it's better to just increase stack size?

**Comment by Graur** [comment]
@yegor256 `switch` object checks all cases no matter of result. While `if` objects chain stops the execution in some cases. I believe with `if` objects it should work faster.

**Comment by Graur** [comment]
@maxonfjvipon No, we can use it. Looks like extra stack memory is a better solution

**Pull request closed without merging**
