### PR TITLE
removed overrides of all the other localisation settings

### PR DESCRIPTION
**Pull request by Graur**
#28

### CODE REVIEW

**Comment by Graur** [comment]
@yegor256 or @maxonfjvipon please merge it, but without `rultor merge`. I believe this should solve #28

**Comment by maxonfjvipon** [comment]
@Graur I don't have "write access", @yegor256 it's yours

**Comment by Graur** [comment]
@yegor256 please, check

**Comment by yegor256** [comment]
@Graur done

**Pull request merged**
