### PR TITLE
splitted number-tests to avoid StackOverflow error

### PR DESCRIPTION
**Pull request by Graur**
#71 

I tried to split large `number-tests.eo` file. It should help to avoid StackOverflow Exception

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@Graur did you see that: Error:  [org.eolang.math.number-tests:25] The alias "org.eolang.math.e" is not used (unused-aliases:27)?

**Comment by Graur** [comment]
@maxonfjvipon Yep, thanks

**Comment by maxonfjvipon** [comment]
@Graur do you think this is about splitting tests, not renaming?

**Comment by Graur** [comment]
@maxonfjvipon I guess so

**Comment by maxonfjvipon** [comment]
@Graur maybe rename these log tests back then?

**Comment by Graur** [comment]
@maxonfjvipon It's a flaky tests

**Comment by maxonfjvipon** [comment]
@Graur can you please explain what do you mean when you say `flaky`?

**Comment by maxonfjvipon** [comment]
@Graur do you have an idea what can be a reason?

**Comment by Graur** [comment]
@maxonfjvipon Unfortunately I don't know yet

**Pull request closed without merging**
