### PR TITLE
Reorder metas

### PR DESCRIPTION
**Pull request by kerelape**

### CODE REVIEW

**Comment by kerelape** [comment]
#25 A part of the task is already done here

**Comment by Graur** [comment]
@rultor merge

**Comment by Graur** [comment]
@rultor merge

**Comment by Graur** [comment]
@kerelape We are having trouble merging in this repository. I hope this will be resolved soon

**Comment by Graur** [comment]
@rultor merge

**Comment by Graur** [comment]
@kerelape Thanks!

**Pull request merged**
